spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ts123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest 
  jpa:
    show-sql: true
